// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/example/error": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Example"
                ],
                "summary": "错误（接口不会暴露错误信息，应对一些未知或未处理的错误）",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/example/error/custom": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Example"
                ],
                "summary": "自定义错误（接口会暴露错误信息，需要定义好错误的相关信息）",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/example/helloworld": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Example"
                ],
                "summary": "hello world",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/example/middleware": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Example"
                ],
                "summary": "中间件",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/example/mysql": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Example"
                ],
                "summary": "mysql示例",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/example/redis": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Example"
                ],
                "summary": "redis示例",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "gin-api",
	Description:      "gin-api is a basic api framework developed based on gin",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
